### ISSUE TITLE
源码有么

### ISSUE THREAD

**Issue by 15615833080** [huangyaomian/cainiao5_hym#1]
你好，想要一份源码。可以有偿

**Comment by huangyaomian** [comment]
可以自己在github上找&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月11日(星期五) 下午3:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [huangyaomian/cainiao5_hym] 源码有么 (#1)





 
你好，想要一份源码。可以有偿

**Comment by 15615833080** [comment]
找了，没找到一个全的。老哥多提交啊

**Comment by huangyaomian** [comment]
我也是自己慢慢学习敲的代码，我可以帮你在github找找



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月11日(星期五) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huangyaomian/cainiao5_hym] 源码有么 (#1)





 
找了，没找到一个全的。老哥多提交啊

**Comment by Tea-sc** [comment]
兄弟，我最近也在学习这课，代码敲差不多了，可以交流一下吗

**Comment by huangyaomian** [comment]
我才剛剛的可是敲一些代碼&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月14日(星期一) 中午1:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huangyaomian/cainiao5_hym] 源码有么 (#1)





 
兄弟，我最近也在学习这课，代码敲差不多了，可以交流一下吗

**Comment by Tea-sc** [comment]
> 我才刚刚的只是敲了一些代码 
> […](#)
> ------------------ 原始邮件 ------------------- 发件人：***@ ***.***>; 发送时间：2021年6月14日（星期一）中午1:27 发射：***@***.***>; 抄送：***@***.***>; ***@***.***>; 主题：回复：[huangyaomian/cainiao5_hym]源码有么( #1 )兄弟，我最近一起学习这课，代码敲差不多了，可以交流一下吗——你收到这个是因为你评论了。直接回复此邮件，在 GitHub 上查看，或取消订阅。

你是有课程权限吗？我最近在改写这个项目，嵌套webview会内存溢出，挺难搞

**Comment by huangyaomian** [comment]
> > 我才刚刚的只是敲了一些代码 
> > […](#)
> > ------------------ 原始邮件 ------------------- 发件人：_**@ _**.**_>; 发送时间：2021年6月14日（星期一）中午1:27 发射：**_@_**.**_>; 抄送：_**@**_._**>; _**@**_.**_>; 主题：回复：[huangyaomian/cainiao5_hym]源码有么( #1 )兄弟，我最近一起学习这课，代码敲差不多了，可以交流一下吗——你收到这个是因为你评论了。直接回复此邮件，在 GitHub 上查看，或取消订阅。
> 
> 你是有课程权限吗？我最近在改写这个项目，嵌套webview会内存溢出，挺难搞

请问你有课程权限吗？ 我没有token可用
